name: Manual Trigger with Params

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        type: string
      greeting:
        description: 'Type of greeting (e.g., Hello, Hi, Welcome)'
        required: true
        type: string
      data:
        description: 'Base64 encoded content of a file'
        required: false
        type: string
      
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Decode File content
        if: ${{ inputs.data }}
        run: |
          echo "${{ inputs.data }}" | base64 --decode > ./decoded_file.txt
      - name: Display Greeting
        run: |
          echo "${{ inputs.greeting }}, ${{ inputs.name }}!"
      - name: Display File content
        if: ${{ inputs.data }}
        run: |
          echo "Content of the file:"
          cat ./decoded_file.txt